### PR TITLE
Update MELPA URL

### PR DESCRIPTION
**Pull request by syohex**

### CODE REVIEW

**Comment by mkmcc** [comment]
didn't know about that... thanks!

**Comment by mkmcc** [comment]
Hi syohex, I did this late at night, and think I accidentally closed your pull request instead of applying it!  I'm so sorry about that.  If you redo the request, I'll apply it correctly this time.

apologies again for the mistake,
Mike

**Comment by syohex** [comment]
@mkmcc no problem. I have sent PR #8 again. Please check it.

**Comment by mkmcc** [comment]
thanks.  apologies again!

**Pull request closed without merging**
